### ISSUE TITLE
List users (types) _Ex. doctors, nurses, etc..._

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#1]
### Example:
-  [from Twitter](https://twitter.com/DeepAshanaMD/status/1242229204948865025)
- [Covide-19 Affects Mental Health](https://www.mdmag.com/medical-news/covid-19-affects-mental-health-nurses-frontline-more)
## Ask
Please make a list of our target audience. This will also be used to make specific channels within the community. They can be added as comments below.

**Comment by ameeker** [comment]
Doctors
Nurses
Nurse Practioners
Nurses Aides
Hospitalists
Pediatricians
Lic. Counselors
LSW
Hospital Administrators
Anesthesiologists

**Comment by ademeglio** [comment]
@ameeker Please go ahead and add these to the Wiki page. I think Merry may have put some of these there already.

**Comment by ademeglio** [comment]
We have a great starting list that I used to create Topic channels in Mattermost.
