### ISSUE TITLE
Wire Frame pages we now need.

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#15]
We now need to add additional pages that are related to Mattermost.
- [ ] Welcome Page
- [ ] Help Page with a FAQ (We can't change the text of the link on the Mattermost sign in page).
- [ ] Terms of Service Page. _Must include text of Mattermost's ToS.
- [ ] Privacy Page. _Reference Mattermost privacy page_
- [ ] About Page. 
- [ ] Mattermost Sign In Page

**Comment by evadale** [comment]
Met with @nenafay and @TLGwegg to talk about the Info site.
We are aiming to have a prototype of the front page (mobile and desktop) to show for the Wednesday, April 22 meeting.

**Comment by evadale** [comment]
For Wednesday, April 22 @nenafay is going to:
- build an html draft of the front page - mobile and desktop

Additional items, time permitting:
- test embedding a google form into an inside page
- build inside page - mobile and desktop

**Comment by evadale** [comment]
For Wednesday, April 22 @TLGwegg  is going to:
- finish design of front page - mobile and desktop

Additional item, time permitting:
- design inside page - mobile and desktop

**Comment by evadale** [comment]
For Wednesday, April 22 @evadale  is going to:
- provide content for front page

Additional items, time permitting:
- draft navigation for site
- draft content for inside pages

**Comment by evadale** [comment]
Content is more or less ready. I've roughed it out and am open for feedback.
https://docs.google.com/document/d/1zgTyQtoSCDLYerHiMvQIs7o5Swtp1UW0djOf3iM5pOw/edit?usp=sharing
