### ISSUE TITLE
Central Ohio Logo

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#19]
> Hey team, for the workspace/team in Mattermost, it would be nice to have a square image we can use. If we are going with Central Ohio, I was thinking a logo of the state with a band across, representing the mid ohio region. Any takers? Colors would stay on brand.

Info about the icon from Mattermost:
>Your Team Icon appears in the team sidebar, visible if users are members of more than one team.

>You can upload a team icon in BMP, JPG or PNG format. Square images with a solid background color are recommended, since transparency in PNG icons fills with a white background in the Team Sidebar. Removing the team icon resets it to the default icon that contains the first two letters of the team name.

**Comment by TLGwegg** [comment]
![Central-Ohio-Logo-01](https://user-images.githubusercontent.com/10741165/80716824-20ff9580-8ac6-11ea-951c-6c4e8a27b37a.png)
![Central-Ohio-Logo-03](https://user-images.githubusercontent.com/10741165/80716827-21982c00-8ac6-11ea-9881-be83aad583f6.png)
![Central-Ohio-Logo-02](https://user-images.githubusercontent.com/10741165/80716828-21982c00-8ac6-11ea-9157-ddaca6cf68ff.png)

Is this what you had in mind? Thanks.

**Comment by TLGwegg** [comment]
![image](https://user-images.githubusercontent.com/10741165/80723409-9a02eb00-8ace-11ea-992f-3e623825468b.png)
![Central-Ohio-Logo-04](https://user-images.githubusercontent.com/10741165/80723427-9f603580-8ace-11ea-9c50-d482b9b5cd4f.png)

What about this?

**Comment by ademeglio** [comment]
I'm not crazy about the square. Is it trying to highlight the region? I do
like where you are headed with it. How would it work if we expended to
other regions?

**Comment by TLGwegg** [comment]
Something like this. 
![image](https://user-images.githubusercontent.com/10741165/80725453-172f5f80-8ad1-11ea-9d23-b4e59de7410e.png)

**Comment by ademeglio** [comment]
Cool. OK, let's just roll with it then. :-)

**Comment by ademeglio** [comment]
and THANK YOU!
