### ISSUE TITLE
List front line healthcare topics

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#2]
## Ask
We need to create a list of basic topics to consider for additional topic channels.

**Comment by ameeker** [comment]
Equipment Needs and Requests
Telehealth Questions and Best Practices
Testing and Evaluation
Personal Safety
Social Welfare and Employment
(all taken from topics addressed at https://www.ama-assn.org/delivering-care/public-health/covid-19-2019-novel-coronavirus-resource-center-physicians)

**Comment by ameeker** [comment]
Personal Wellness

**Comment by ameeker** [comment]
Request for Help

**Comment by ademeglio** [comment]
@ameeker Could you also add these to the Wiki page please. Let me know if need any assistance. I added some more details to the home page. Thank you.

**Comment by ademeglio** [comment]
Looks like it was completed. I cleaned up formatting a little bit in the wiki.
