### ISSUE TITLE
Info Site Notes

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#28]
- [x] Header. The Frontline logo should always link back to `index.html`.
- [x] index.html#Contact Us. Add `target="_blank"` to email address. 
- [x] Footer. Add `target="_blank"` to email address.  
  - However, we could consider a form with a recaptcha to limit spam. If we agree, create a new issue.
- [x] missing `apply.html`
  - Should we put together a new google form and embed into that page?
-  ~Custom 404 Page~ (Create new issue)
- [x] index.html#ConnectingCommunities `view full list` link broken or page doesn't exist?
- [x] Index, spelling of across in mission statement.

**Comment by nenafay** [comment]
- [x] desktop view nav should line up with blue bar on R side.
- [x] all links should remain the same in nav. 
- [x] current page should be highlighted in nav.
- [x] alter mobile dropdown nav stylings according to Eva's specifications
- [x] Trim space around separate elements on front page.
- [x] Fix javascript on menu bars container
- [x] Center "Try the App" button
- [x] Center communities content
- [x] fix can't stop cbus logo in footer.
