### ISSUE TITLE
User Research - What do the users think they need?

### ISSUE THREAD

**Issue by ademeglio** [ademeglio/the-frontline#6]
We know we have two core groups to connect, but what are their stated communication needs.

### Add references:

**Comment by merrymelle** [comment]
I think a big issue is the ability to get fast and accurate information between facilities and disciplines is key. Hospital administration is not always transparent or timely on the facts, disciplines don't have time to fully communicate in person (esp now!) and many professionals lack contacts at other facilities. 

I feel the biggest need is to allow professionals to collect all collateral so they can see the big picture of how COVID19 is affecting the area so they can prep & treat as best they can. It will help their mental state to be informed as possible, create a support network between them and allow them to provide best care possible. 

Reference: myself & my personal experience :) (healthcare worker)

**Comment by ademeglio** [comment]
We've received 11 responses to the new survey as of 4/10/2020. Braden is going to review written answers to see if he can glean any additional information.
